run.sh: Use ISO timestamp with timezone and usec precision
This is what HA expects to receive otherwise it would fail with:

  ValueError: Invalid datetime: sensor.bresser_5_in_1_utc provides
  state '2022-12-31 05:33:33', which is missing timezone information

See: https://github.com/merbanan/rtl_433/issues/2293